// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wyyswujvinxkvvigfsbk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5eXN3dWp2aW54a3Z2aWdmc2JrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0MzU1NzIsImV4cCI6MjA2MjAxMTU3Mn0.WtcbJ0X1pT7zGCYAgWdjkaG5fesEZTzdsp_DFPNRq_A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);